
files:
  upload:
    location: D:/programing/IdeaProjects/work4/videos-website/src/main/resources/static/image/
    path: /image/**
    location-video: D:/programing/IdeaProjects/work4/videos-website/src/main/resources/static/video/
    path-video: /video/**

spring:
  datasource:
    url: jdbc:mysql://47.113.188.125:3306/videos_website?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 8472554Lcy
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
  redis:
    host: 47.113.188.125
    port: 6379
    password: 8472554Lcy

  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 2GB



mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 10001
  address: 0.0.0.0
